name: Deploy Zappa Lambdas to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'src/lambda_functions/**'
      - 'src/zappa_settings.json'
      - 'src/environment.yml'
      - '.github/workflows/deploy-lambdas.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }} # Lee la región de los GitHub Secrets

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.9
        environment-file: src/environment.yml
        activate-environment: parcial3_env
        auto-activate-base: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }} # Usa la variable de entorno del job

    - name: Configure Zappa Settings for CI/CD
      run: |
        cd src
        # Reemplazar placeholders en zappa_settings.json con los valores de GitHub Secrets
        sed -i 's|DUMMY_S3_ZAPPA_DEPLOY_BUCKET|${{ secrets.S3_ZAPPA_DEPLOY_BUCKET }}|g' zappa_settings.json
        sed -i 's|DUMMY_S3_DATA_BUCKET|${{ secrets.S3_DATA_BUCKET }}|g' zappa_settings.json
        sed -i 's|DUMMY_S3_GLUE_SCRIPTS_BUCKET|${{ secrets.S3_GLUE_SCRIPTS_BUCKET }}|g' zappa_settings.json
        sed -i 's|DUMMY_S3_EMR_LOGS_BUCKET|${{ secrets.S3_EMR_LOGS_BUCKET }}|g' zappa_settings.json
        sed -i 's|DUMMY_GLUE_CRAWLER_NAME|${{ secrets.GLUE_CRAWLER_NAME }}|g' zappa_settings.json
        sed -i 's|DUMMY_GLUE_RDS_CONNECTION_NAME|${{ secrets.GLUE_RDS_CONNECTION_NAME }}|g' zappa_settings.json
        sed -i 's|DUMMY_EMR_CLUSTER_NAME|${{ secrets.EMR_CLUSTER_NAME }}|g' zappa_settings.json
        sed -i 's|DUMMY_EMR_RELEASE_LABEL|${{ secrets.EMR_RELEASE_LABEL }}|g' zappa_settings.json
        sed -i 's|DUMMY_EC2_SUBNET_ID|${{ secrets.EC2_SUBNET_ID }}|g' zappa_settings.json
        sed -i 's|DUMMY_EC2_KEY_PAIR|${{ secrets.EC2_KEY_PAIR }}|g' zappa_settings.json
        sed -i 's|DUMMY_EMR_SERVICE_ROLE|${{ secrets.EMR_SERVICE_ROLE }}|g' zappa_settings.json
        sed -i 's|DUMMY_EC2_INSTANCE_PROFILE|${{ secrets.EC2_INSTANCE_PROFILE }}|g' zappa_settings.json
        sed -i 's|DUMMY_S3_SCRIPT_LOCATION|${{ secrets.S3_SCRIPT_LOCATION }}|g' zappa_settings.json
        sed -i 's|DUMMY_BOOTSTRAP_ACTION_PATH|${{ secrets.BOOTSTRAP_ACTION_PATH }}|g' zappa_settings.json
        
        # Imprime el zappa_settings.json final para depuración
        cat zappa_settings.json

    - name: Run Unit Tests (Lambda Functions)
      run: |
        pytest tests/unit/lambda_functions/
      working-directory: ${{ github.workspace }}

    - name: Deploy Zappa Lambdas
      run: |
        cd src
        zappa update dev --json